\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		% intro
		g1 g1

		% hemos entrado...
		g1 d1 e1:m d1
		g1 d1 e1:m d1

		% para estar...
		a2:m b2:m c2 d2
		a2:m b2:m c2 d1

		% somos incienso...
		g1 d1 e1:m c1
		g1 d1 e1:m
		g1 d1 e1:m c1
		g1 d1 c1 g1

		g1 g1

		% hemos entrado...
		g1 d1 e1:m d1
		g1 d1 e1:m d1

		% para estar...
		a2:m b2:m c2 d2
		a2:m b2:m c2 d1

		% somos incienso...
		g1 d1 e1:m c1
		g1 d1 e1:m
		g1 d1 e1:m c1
		g1 d1 c1 g1

		g1
	}
